### ISSUE TITLE
ofAppRunner - Problem with fullscreen mode on Ubuntu

### ISSUE THREAD

**Issue by pbaret** [openframeworks/ofSite#570] opened 2016-11-15 14:21 UTC
Hi,

I have a probleme on Ubuntu with ofSetFullscreen. I am running the window example. It is compiling and running fine but when I press  'f'   to go in fullscreen mode, the framerate suddenly drops to less than 1 fps...  And it is the same for every other example which have a fullscreen mode...

I really don't know what to do.

Thanks in advance for any help.

**Comment by arturoc** [comment] 2016-11-16 14:22
can you try if the nightly builds have the same problem?

**Comment by pbaret** [comment] 2016-11-16 15:56
I tried with the last version on github and the last release from of website.

Le 16 nov. 2016 15:22, arturo <notifications@github.com> a écrit :

can you try if the nightly builds have the same problem?

**Comment by arturoc** [comment] 2016-11-17 13:55
i'm going to close this issue as duplicate of https://github.com/openframeworks/openFrameworks/issues/5350#issuecomment-261167178 since that one has more info and is in the correct repo (this one is in the site repository no the OF core one). if you have any other information or comment please use that other issue. thanks!

**Closed by arturoc** 2016-11-17 13:55 UTC
